### PR TITLE
fixed todo's broken link to google python styleguide

### PR DESCRIPTION
**Pull request by nskeip**
http://google-styleguide.googlecode.com/svn/trunk/pyguide.html gave 404,
replacing it with https://google.github.io/styleguide/pyguide.html

### CODE REVIEW

**Comment by aikoven** [comment]
Hey, thank you for your PRs, but I have no plans to maintain this repo. You can continue development in your own fork, or I can transfer ownership to you.

**Comment by nskeip** [comment]
Hello!

If you transferred the ownership, I would appreciate that.

Maria Grechkoseeva and Natalia Maslova came up with some feature requests, so it would be very convenient for me as a developer to own that repo.

PS: realy nice work you've done!

**Comment by aikoven** [comment]
GitHub gives me this error:

> nskeip already has a repository in the aikoven/calculations network

Could you maybe try to delete your current fork?

**Comment by nskeip** [comment]
> Could you maybe try to delete your current fork?

Oh, sure. Done.

**Comment by aikoven** [comment]
> Repository transfer to nskeip requested

Please check your inbox.

**Comment by aikoven** [comment]
It seems to have worked, thanks. Good luck 🙂

**Comment by nskeip** [comment]
Thanks!

**Pull request merged**
